services:
  auth:
    image: auth:${APP_IMAGE_TAG}
    container_name: auth
    restart: unless-stopped
    env_file:
      - .env.${ENV}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    networks:
      - service-network
    depends_on:
      db-auth:
        condition: service_healthy
      migrator-auth:
        condition: service_completed_successfully

  db-auth:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: db-auth
    restart: unless-stopped
    env_file:
      - .env.${ENV}
    # expose:
    #   - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT}"
    networks:
      - service-network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  redis-auth:
    image: redis:${REDIS_IMAGE_TAG}
    container_name: redis-auth
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    restart: unless-stopped
    env_file:
      - .env.${ENV}
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    # expose:
    #   - ${REDIS_PORT}
    ports:
      - "${REDIS_PORT_LOCAL}:${REDIS_PORT}"
    networks:
      - service-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  migrator-auth:
    image: migrator-auth:${MIGRATOR_IMAGE_TAG}
    container_name: migrator-auth
    restart: on-failure
    environment:
      DB_HOST: db-auth
    networks:
      - service-network
    depends_on:
      db-auth:
        condition: service_healthy

volumes:
  postgres_volume:

networks:
  service-network:
    name: service-net
    external: true
