services:
  auth:
    image: auth:${APP_IMAGE_TAG}
    container_name: auth
    env_file:
      - .env.${ENV}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    networks:
      - service-network
    depends_on:
      db-auth:
        condition: service_healthy
      migrator-auth:
        condition: service_completed_successfully

  db-auth:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: db-auth
    env_file:
      - .env.${ENV}
    ports:
      - "${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT}"
    networks:
      - service-network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  redis-auth:
    image: redis:latest
    container_name: redis-auth
    env_file:
    - .env.${ENV}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - service-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  migrator-auth:
    image: migrator-auth:${MIGRATOR_IMAGE_TAG}
    container_name: migrator-auth
    restart: on-failure
    environment:
      DB_HOST: db-auth
    networks:
      - service-network
    depends_on:
      db-auth:
        condition: service_healthy

volumes:
  postgres_volume:

networks:
  service-network:
    name: service-net
    external: true