// access.proto
// This file defines the Access API v1,
// which handles user authorization for various service endpoints.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: access.proto

package access_v1

import (
	v1 "github.com/8thgencore/microservice-auth/pkg/pb/user/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckRequest contains the endpoint a user is trying to access.
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endpoint where the user wants access.
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// AddRoleEndpointRequest represents the request to add roles to an endpoint.
type AddRoleEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endpoint to which roles will be added.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The roles allowed to access this endpoint.
	AllowedRoles  []v1.Role `protobuf:"varint,2,rep,packed,name=allowed_roles,json=allowedRoles,proto3,enum=user_v1.Role" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleEndpointRequest) Reset() {
	*x = AddRoleEndpointRequest{}
	mi := &file_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleEndpointRequest) ProtoMessage() {}

func (x *AddRoleEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleEndpointRequest.ProtoReflect.Descriptor instead.
func (*AddRoleEndpointRequest) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{1}
}

func (x *AddRoleEndpointRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AddRoleEndpointRequest) GetAllowedRoles() []v1.Role {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

// UpdateRoleEndpointRequest represents the request to update roles for an endpoint.
type UpdateRoleEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endpoint to be updated.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The updated roles for this endpoint.
	AllowedRoles  []v1.Role `protobuf:"varint,2,rep,packed,name=allowed_roles,json=allowedRoles,proto3,enum=user_v1.Role" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleEndpointRequest) Reset() {
	*x = UpdateRoleEndpointRequest{}
	mi := &file_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleEndpointRequest) ProtoMessage() {}

func (x *UpdateRoleEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleEndpointRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleEndpointRequest) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoleEndpointRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *UpdateRoleEndpointRequest) GetAllowedRoles() []v1.Role {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

// DeleteRoleEndpointRequest represents the request to delete an endpoint permission.
type DeleteRoleEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endpoint to be deleted.
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleEndpointRequest) Reset() {
	*x = DeleteRoleEndpointRequest{}
	mi := &file_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleEndpointRequest) ProtoMessage() {}

func (x *DeleteRoleEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleEndpointRequest) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRoleEndpointRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// GetRoleEndpointsResponse represents the response containing a list of endpoint permissions.
type GetRoleEndpointsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of endpoint permissions.
	EndpointPermissions []*EndpointPermissions `protobuf:"bytes,1,rep,name=endpoint_permissions,json=endpointPermissions,proto3" json:"endpoint_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRoleEndpointsResponse) Reset() {
	*x = GetRoleEndpointsResponse{}
	mi := &file_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleEndpointsResponse) ProtoMessage() {}

func (x *GetRoleEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleEndpointsResponse.ProtoReflect.Descriptor instead.
func (*GetRoleEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoleEndpointsResponse) GetEndpointPermissions() []*EndpointPermissions {
	if x != nil {
		return x.EndpointPermissions
	}
	return nil
}

// EndpointPermissions represents the permission settings for an endpoint.
type EndpointPermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endpoint being described.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The roles allowed to access this endpoint.
	AllowedRoles  []v1.Role `protobuf:"varint,2,rep,packed,name=allowed_roles,json=allowedRoles,proto3,enum=user_v1.Role" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointPermissions) Reset() {
	*x = EndpointPermissions{}
	mi := &file_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointPermissions) ProtoMessage() {}

func (x *EndpointPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointPermissions.ProtoReflect.Descriptor instead.
func (*EndpointPermissions) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{5}
}

func (x *EndpointPermissions) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *EndpointPermissions) GetAllowedRoles() []v1.Role {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

var File_access_proto protoreflect.FileDescriptor

const file_access_proto_rawDesc = "" +
	"\n" +
	"\faccess.proto\x12\taccess_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"user.proto\x1a\x17validate/validate.proto\"J\n" +
	"\fCheckRequest\x12:\n" +
	"\bendpoint\x18\x01 \x01(\tB\x1e\xfaB\x1br\x19\x10\x01\x18\xff\x012\x12^[a-zA-Z0-9_/.-]+$R\bendpoint\"\x92\x01\n" +
	"\x16AddRoleEndpointRequest\x12:\n" +
	"\bendpoint\x18\x01 \x01(\tB\x1e\xfaB\x1br\x19\x10\x01\x18\xff\x012\x12^[a-zA-Z0-9_/.-]+$R\bendpoint\x12<\n" +
	"\rallowed_roles\x18\x02 \x03(\x0e2\r.user_v1.RoleB\b\xfaB\x05\x92\x01\x02\b\x01R\fallowedRoles\"\x95\x01\n" +
	"\x19UpdateRoleEndpointRequest\x12:\n" +
	"\bendpoint\x18\x01 \x01(\tB\x1e\xfaB\x1br\x19\x10\x01\x18\xff\x012\x12^[a-zA-Z0-9_/.-]+$R\bendpoint\x12<\n" +
	"\rallowed_roles\x18\x02 \x03(\x0e2\r.user_v1.RoleB\b\xfaB\x05\x92\x01\x02\b\x01R\fallowedRoles\"W\n" +
	"\x19DeleteRoleEndpointRequest\x12:\n" +
	"\bendpoint\x18\x01 \x01(\tB\x1e\xfaB\x1br\x19\x10\x01\x18\xff\x012\x12^[a-zA-Z0-9_/.-]+$R\bendpoint\"m\n" +
	"\x18GetRoleEndpointsResponse\x12Q\n" +
	"\x14endpoint_permissions\x18\x01 \x03(\v2\x1e.access_v1.EndpointPermissionsR\x13endpointPermissions\"\x8f\x01\n" +
	"\x13EndpointPermissions\x12:\n" +
	"\bendpoint\x18\x01 \x01(\tB\x1e\xfaB\x1br\x19\x10\x01\x18\xff\x012\x12^[a-zA-Z0-9_/.-]+$R\bendpoint\x12<\n" +
	"\rallowed_roles\x18\x02 \x03(\x0e2\r.user_v1.RoleB\b\xfaB\x05\x92\x01\x02\b\x01R\fallowedRoles2\xc2\x04\n" +
	"\bAccessV1\x12U\n" +
	"\x05Check\x12\x17.access_v1.CheckRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/access/check\x12q\n" +
	"\x0fAddRoleEndpoint\x12!.access_v1.AddRoleEndpointRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/access/role-endpoint\x12w\n" +
	"\x12UpdateRoleEndpoint\x12$.access_v1.UpdateRoleEndpointRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/access/role-endpoint\x12\x7f\n" +
	"\x12DeleteRoleEndpoint\x12$.access_v1.DeleteRoleEndpointRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%*#/v1/access/role-endpoint/{endpoint}\x12r\n" +
	"\x10GetRoleEndpoints\x12\x16.google.protobuf.Empty\x1a#.access_v1.GetRoleEndpointsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/access/role-endpointsBDZBgithub.com/8thgencore/microservice-auth/pkg/pb/access/v1;access_v1b\x06proto3"

var (
	file_access_proto_rawDescOnce sync.Once
	file_access_proto_rawDescData []byte
)

func file_access_proto_rawDescGZIP() []byte {
	file_access_proto_rawDescOnce.Do(func() {
		file_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_proto_rawDesc), len(file_access_proto_rawDesc)))
	})
	return file_access_proto_rawDescData
}

var file_access_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_access_proto_goTypes = []any{
	(*CheckRequest)(nil),              // 0: access_v1.CheckRequest
	(*AddRoleEndpointRequest)(nil),    // 1: access_v1.AddRoleEndpointRequest
	(*UpdateRoleEndpointRequest)(nil), // 2: access_v1.UpdateRoleEndpointRequest
	(*DeleteRoleEndpointRequest)(nil), // 3: access_v1.DeleteRoleEndpointRequest
	(*GetRoleEndpointsResponse)(nil),  // 4: access_v1.GetRoleEndpointsResponse
	(*EndpointPermissions)(nil),       // 5: access_v1.EndpointPermissions
	(v1.Role)(0),                      // 6: user_v1.Role
	(*emptypb.Empty)(nil),             // 7: google.protobuf.Empty
}
var file_access_proto_depIdxs = []int32{
	6, // 0: access_v1.AddRoleEndpointRequest.allowed_roles:type_name -> user_v1.Role
	6, // 1: access_v1.UpdateRoleEndpointRequest.allowed_roles:type_name -> user_v1.Role
	5, // 2: access_v1.GetRoleEndpointsResponse.endpoint_permissions:type_name -> access_v1.EndpointPermissions
	6, // 3: access_v1.EndpointPermissions.allowed_roles:type_name -> user_v1.Role
	0, // 4: access_v1.AccessV1.Check:input_type -> access_v1.CheckRequest
	1, // 5: access_v1.AccessV1.AddRoleEndpoint:input_type -> access_v1.AddRoleEndpointRequest
	2, // 6: access_v1.AccessV1.UpdateRoleEndpoint:input_type -> access_v1.UpdateRoleEndpointRequest
	3, // 7: access_v1.AccessV1.DeleteRoleEndpoint:input_type -> access_v1.DeleteRoleEndpointRequest
	7, // 8: access_v1.AccessV1.GetRoleEndpoints:input_type -> google.protobuf.Empty
	7, // 9: access_v1.AccessV1.Check:output_type -> google.protobuf.Empty
	7, // 10: access_v1.AccessV1.AddRoleEndpoint:output_type -> google.protobuf.Empty
	7, // 11: access_v1.AccessV1.UpdateRoleEndpoint:output_type -> google.protobuf.Empty
	7, // 12: access_v1.AccessV1.DeleteRoleEndpoint:output_type -> google.protobuf.Empty
	4, // 13: access_v1.AccessV1.GetRoleEndpoints:output_type -> access_v1.GetRoleEndpointsResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_access_proto_init() }
func file_access_proto_init() {
	if File_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_proto_rawDesc), len(file_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_access_proto_goTypes,
		DependencyIndexes: file_access_proto_depIdxs,
		MessageInfos:      file_access_proto_msgTypes,
	}.Build()
	File_access_proto = out.File
	file_access_proto_goTypes = nil
	file_access_proto_depIdxs = nil
}
