{
 "title": "Auth service overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Incoming traffic (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(auth_grpc_auth_service_requests_total[5s])",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Outcoming traffic (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(auth_grpc_auth_service_responses_total[10s])",
     "legendFormat": "{{status}}:{{method}}"
    }
   ]
  },
  {
   "title": "Quantiles of response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    sum(rate(auth_grpc_auth_service_histogram_response_time_seconds_bucket[10s])) by (le, status)\n)",
     "legendFormat": "0.9q: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.5,\n    sum(rate(my_space_grpc_my_app_histogram_response_time_seconds_bucket[10s])) by (le, status)\n)",
     "legendFormat": "0.5q: {{status}}"
    }
   ]
  }
 ]
}